/**
 * API-First POC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    /**
     * Unique identifier for the user
     */
    id: number;
    /**
     * The user\'s name
     */
    name: string;
    /**
     * The user\'s email address
     */
    email?: string;
}

